spring:
  profiles:
    include: secret  # 로컬의 application-secret.yml을 로드 (보안 상 git 제외 대상)

  application:
    name: codereferee-server

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/codereferee_test
    username: ryu
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none # 추후에 update로 변경
    show-sql: true
    properties:
      hibernate:
        format_sql: true # 로그 가독성 향상

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: prometheus

ai:
  core:
    enabled: false
    base-url: http://192.168.185.48:8000
    repository-validation-path: /v1/validations/repository
