spring:
  profiles:
    include: secret  # 로컬의 application-secret.yml을 로드 (보안 상 git 제외 대상)
  application:
    name: codereferee-server

  datasource:
    url: jdbc:postgresql://localhost:5432/codereferee-db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # 추후에 update로 변경
    show-sql: true
    properties:
      hibernate:
        format_sql: true # 로그 가독성 향상

server:
  port: 8080